# Feature Engineering Notebook
Load preprocessed data from EDA and create new features for ML models

## Step 1: Setup and Imports

In [5]:
import pandas as pd
import numpy as np
from pathlib import Path
import sys
import os

# Add project root to path
sys.path.append(os.path.abspath(".."))

print("✅ Imports successful")

✅ Imports successful

## Step 2: Load Preprocessed Data from Parquet

In [6]:
# Define paths using pathlib (production-standard approach)
PROJECT_ROOT = Path('..')
DATA_DIR = PROJECT_ROOT / 'data'
DF_EDA_PATH = DATA_DIR / 'df_eda_features.parquet'

# Load the parquet file
df = pd.read_parquet(DF_EDA_PATH)

print(f"✅ Loaded data from {DF_EDA_PATH}")
print(f"Shape: {df.shape}")
print(f"\nColumns: {df.columns.tolist()}")
print(f"\nData types:\n{df.dtypes}")

✅ Loaded data from ../data/df_eda_features.parquet
Shape: (51376, 13)

Columns: ['created', 'id', 'sp_futures', 'dow_futures', 'nasdaq_futures', 'gold', 'russell_2000', 'vix', 'time_diff', 'time_diff_seconds', 'rolling_mean_60', 'rolling_std_60', 'price_change']

Data types:
created              datetime64[us, UTC]
id                                 int64
sp_futures                       float64
dow_futures                      float64
nasdaq_futures                   float64
gold                             float64
russell_2000                     float64
vix                              float64
time_diff                timedelta64[us]
time_diff_seconds                float64
rolling_mean_60                  float64
rolling_std_60                   float64
price_change                     float64
dtype: object

## Step 3: Explore Loaded Data

In [7]:
# Display first few rows
df.head(10)

,created,id,sp_futures,dow_futures,nasdaq_futures,gold,russell_2000,vix,time_diff,time_diff_seconds,rolling_mean_60,rolling_std_60,price_change
0,2026-02-13 17:32:22.575870+00:00,1681,6879.18,49682.86,22739.69,5037.0,2664.63,19.34,NaT,NaN,NaN,NaN,NaN
1,2026-02-13 17:32:29.064421+00:00,1682,6878.68,49681.41,22737.11,5037.3,2664.58,19.34,0 days 00:00:06.488551,6.488551,NaN,NaN,0.3
2,2026-02-13 17:32:35.408570+00:00,1683,6878.68,49682.78,22736.22,5037.3,2664.51,19.36,0 days 00:00:06.344149,6.344149,NaN,NaN,0.0
3,2026-02-13 17:32:41.714729+00:00,1684,6878.62,49680.89,22737.16,5037.3,2664.42,19.36,0 days 00:00:06.306159,6.306159,NaN,NaN,0.0
4,2026-02-13 17:32:47.802792+00:00,1685,6878.92,49681.59,22738.85,5037.2,2664.35,19.36,0 days 00:00:06.088063,6.088063,NaN,NaN,-0.1
5,2026-02-13 17:32:54.122996+00:00,1686,6878.01,49674.49,22739.03,5037.6,2664.18,19.40,0 days 00:00:06.320204,6.320204,NaN,NaN,0.4
6,2026-02-13 17:33:01.195949+00:00,1687,6877.57,49671.25,22735.59,5038.5,2664.15,19.40,0 days 00:00:07.072953,7.072953,NaN,NaN,0.9
7,2026-02-13 17:33:07.300563+00:00,1688,6877.61,49671.05,22734.72,5038.4,2664.13,19.41,0 days 00:00:06.104614,6.104614,NaN,NaN,-0.1
8,2026-02-13 17:33:13.475880+00:00,1689,6878.50,49679.87,22737.65,5038.7,2663.90,19.41,0 days 00:00:06.175317,6.175317,NaN,NaN,0.3
9,2026-02-13 17:33:19.669738+00:00,1690,6878.40,49679.12,22737.27,5038.3,2663.89,19.43,0 days 00:00:06.193858,6.193858,NaN,NaN,-0.4

In [8]:
# Check for missing values
print("Missing values:")
print(df.isnull().sum())
print(f"\nPercentage missing:")
print((df.isnull().sum() / len(df) * 100).round(2))

Missing values:
created                  0
id                       0
sp_futures           11225
dow_futures          11225
nasdaq_futures       11225
gold                     0
russell_2000         11225
vix                      6
time_diff                1
time_diff_seconds        1
rolling_mean_60         59
rolling_std_60          59
price_change             1
dtype: int64

Percentage missing:
created               0.00
id                    0.00
sp_futures           21.85
dow_futures          21.85
nasdaq_futures       21.85
gold                  0.00
russell_2000         21.85
vix                   0.01
time_diff             0.00
time_diff_seconds     0.00
rolling_mean_60       0.11
rolling_std_60        0.11
price_change          0.00
dtype: float64

In [9]:
# Basic statistics
df.describe()

,id,sp_futures,dow_futures,nasdaq_futures,gold,russell_2000,vix,time_diff,time_diff_seconds,rolling_mean_60,rolling_std_60,price_change
count,51376.000000,40151.000000,40151.000000,40151.000000,51376.000000,40151.000000,51370.000000,51375,5.137500e+04,51317.000000,51317.000000,51375.000000
mean,27368.500000,6820.151565,48718.881848,22669.843172,4894.039382,2633.131004,20.612198,0 days 00:01:39.491241,9.949124e+01,4894.030628,1.336195,-0.005263
std,14831.118052,73.912386,1020.432710,291.251463,147.028608,40.173760,2.087587,0 days 03:01:29.743914,1.088974e+04,146.838150,7.682005,2.468858
min,1681.000000,6368.850000,45166.640000,20948.360000,4491.600000,2426.360000,18.760000,0 days 00:00:05.628062,5.628062e+00,4492.000000,0.000000,-420.300000
25%,14524.750000,6816.890000,47916.570000,22546.670000,4787.400000,2630.590000,19.230000,0 days 00:00:06.100607,6.100607e+00,4787.400000,0.000065,0.000000
50%,27368.500000,6836.170000,49500.930000,22645.460000,4836.400000,2646.700000,20.410000,0 days 00:00:06.180217,6.180217e+00,4836.955000,0.000065,0.000000
75%,40212.250000,6836.170000,49500.930000,22902.900000,5046.300000,2646.700000,21.010000,0 days 00:00:06.334564,6.334564e+00,5046.300000,1.311160,0.000000
max,53056.000000,6915.790000,49741.950000,23183.740000,5130.000000,2672.410000,31.050000,24 days 23:28:55.242189,2.158135e+06,5130.000000,210.463876,283.100000

## Step 4: Feature Engineering
Create new features from existing columns for ML models

In [10]:
# Create a copy to preserve original data
df_features = df.copy()

print(f"Original shape: {df.shape}")
print(f"Feature engineering copy shape: {df_features.shape}")

Original shape: (51376, 13)
Feature engineering copy shape: (51376, 13)

### Example Features (customize based on your data)

**Common feature engineering patterns:**
- Polynomial features (squared, cubic)
- Lag features (previous period values)
- Rolling statistics (mean, std, min, max)
- Interaction features (multiply/divide columns)
- Temporal features (hour, day, month from datetime)

In [11]:
# Example 1: Polynomial features (if you have numeric columns)
# Uncomment and modify based on your actual columns

# numeric_cols = df_features.select_dtypes(include=[np.number]).columns
# for col in numeric_cols:
#     df_features[f'{col}_squared'] = df_features[col] ** 2
#     df_features[f'{col}_log'] = np.log1p(df_features[col].abs())  # log1p handles negative values

print("Feature engineering templates ready (uncomment to use)")

Feature engineering templates ready (uncomment to use)

In [12]:
# Example 2: Interaction features
# df_features['feature_interaction'] = df_features['col1'] * df_features['col2']

# Example 3: Lag features (for time series)
# df_features['lag_1'] = df_features['value_col'].shift(1)
# df_features['lag_2'] = df_features['value_col'].shift(2)

# Example 4: Rolling features
# df_features['rolling_mean_7'] = df_features['value_col'].rolling(window=7).mean()
# df_features['rolling_std_7'] = df_features['value_col'].rolling(window=7).std()

print("Add your feature engineering logic here")

Add your feature engineering logic here

In [16]:
df_features.head()

,created,id,sp_futures,dow_futures,nasdaq_futures,gold,russell_2000,vix,time_diff,time_diff_seconds,rolling_mean_60,rolling_std_60,price_change
0,2026-02-13 17:32:22.575870+00:00,1681,6879.18,49682.86,22739.69,5037.0,2664.63,19.34,NaT,NaN,NaN,NaN,NaN
1,2026-02-13 17:32:29.064421+00:00,1682,6878.68,49681.41,22737.11,5037.3,2664.58,19.34,0 days 00:00:06.488551,6.488551,NaN,NaN,0.3
2,2026-02-13 17:32:35.408570+00:00,1683,6878.68,49682.78,22736.22,5037.3,2664.51,19.36,0 days 00:00:06.344149,6.344149,NaN,NaN,0.0
3,2026-02-13 17:32:41.714729+00:00,1684,6878.62,49680.89,22737.16,5037.3,2664.42,19.36,0 days 00:00:06.306159,6.306159,NaN,NaN,0.0
4,2026-02-13 17:32:47.802792+00:00,1685,6878.92,49681.59,22738.85,5037.2,2664.35,19.36,0 days 00:00:06.088063,6.088063,NaN,NaN,-0.1

In [17]:
df_features.isnull().sum()

created                  0
id                       0
sp_futures           11225
dow_futures          11225
nasdaq_futures       11225
gold                     0
russell_2000         11225
vix                      6
time_diff                1
time_diff_seconds        1
rolling_mean_60         59
rolling_std_60          59
price_change             1
dtype: int64

In [ ]:
# Here I want to forward fill the missing values but I want to choose the number of columns to forward fill. I don't want to forward fill all the columns because some of them are not time series data and it doesn't make sense to forward fill them. I will only forward fill the columns that are time series data. I will identify those columns by their names. For example, if the column name contains 'lag' or 'rolling', I will forward fill it. Otherwise, I will leave it as is.

## Step 5: Validate Features

In [13]:
print(f"Final shape: {df_features.shape}")
print(f"Features created: {df_features.shape[1] - df.shape[1]}")
print(f"\nNew columns:\n{df_features.columns.tolist()}")

Final shape: (51376, 13)
Features created: 0

New columns:
['created', 'id', 'sp_futures', 'dow_futures', 'nasdaq_futures', 'gold', 'russell_2000', 'vix', 'time_diff', 'time_diff_seconds', 'rolling_mean_60', 'rolling_std_60', 'price_change']

In [14]:
# Check for inf values
inf_count = np.isinf(df_features.select_dtypes(include=[np.number])).sum().sum()
print(f"Infinite values: {inf_count}")

# Check for NaN after feature engineering
nan_count = df_features.isnull().sum().sum()
print(f"NaN values: {nan_count}")

Infinite values: 0
NaN values: 45027

## Step 6: Save Engineered Features

In [15]:
# Define output path
FEATURES_OUTPUT_PATH = DATA_DIR / 'df_features_engineered.parquet'

# Save the engineered features
df_features.to_parquet(FEATURES_OUTPUT_PATH, index=False)

print(f"✅ Saved engineered features to {FEATURES_OUTPUT_PATH}")
print(f"File size: {FEATURES_OUTPUT_PATH.stat().st_size / (1024**2):.2f} MB")

✅ Saved engineered features to ../data/df_features_engineered.parquet
File size: 2.07 MB

## Summary

✅ Loaded preprocessed data from parquet: `df_eda_features.parquet`  
✅ Performed feature engineering  
✅ Saved engineered features: `df_features_engineered.parquet`  

**Next steps:**
- Load engineered features in ML training notebook
- Split data into train/test
- Train models
- Evaluate performance